// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingPlatform.Infrastructure.Persistence;

#nullable disable

namespace TradingPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingPlatform.Domain.Backtesting.Backtest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeeBps")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("SlippageBps")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Timeframe")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StrategyVersionId");

                    b.HasIndex("UserId");

                    b.ToTable("Backtests", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Backtesting.BacktestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssumptionsJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("AverageLoss")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("AverageWin")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<Guid>("BacktestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeesPaid")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("FinalBalance")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("LargestLosingTrade")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("LargestWinningTrade")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("MaximumDrawdown")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("NetProfit")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<int>("NumberOfTrades")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProfitFactor")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("ReturnPercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("SharpeRatio")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.HasKey("Id");

                    b.HasIndex("BacktestId");

                    b.ToTable("BacktestRuns", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Backtesting.BacktestTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BacktestRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Fees")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PnL")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId");

                    b.ToTable("BacktestTrades", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Balances.Balance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("BotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExchangeAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Free")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Locked")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("ExchangeAccountId", "BotId", "Asset", "Mode")
                        .IsUnique();

                    b.ToTable("Balances", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Balances.BalanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("BotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExchangeAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Free")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Locked")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<decimal>("PortfolioValueQuote")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeAccountId", "SnapshotAt");

                    b.ToTable("BalanceSnapshots", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Bots.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CancelOpenOrdersOnEmergencyStop")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExchangeAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RiskProfileId")
                        .HasColumnType("uuid");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Timeframe")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeAccountId");

                    b.HasIndex("RiskProfileId");

                    b.HasIndex("StrategyVersionId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Bots", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Bots.BotRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StopReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.ToTable("BotRuns", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Exchanges.ExchangeAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CanTrade")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Exchange")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTestnet")
                        .HasColumnType("boolean");

                    b.Property<bool>("LiveEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("ExchangeAccounts", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Exchanges.ExchangeCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("ApiKeyCipher")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ApiSecretCipher")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExchangeAccountId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeAccountId")
                        .IsUnique();

                    b.ToTable("ExchangeCredentials", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorSecretEncrypted")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Market.MarketCandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExchangeTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Low")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Open")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Timeframe")
                        .HasColumnType("integer");

                    b.Property<int?>("TradeCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Volume")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "Timeframe", "OpenTime")
                        .IsUnique();

                    b.ToTable("MarketCandles", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Market.MarketTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExchangeTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ExchangeTradeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBuyerMaker")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "ExchangeTimestamp");

                    b.ToTable("MarketTrades", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Market.Symbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinNotional")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("MinQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PricePrecision")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityPrecision")
                        .HasColumnType("integer");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StepSize")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Symbols", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Market.TimeframeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Timeframe")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Timeframes", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Operations.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Operations.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Operations.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Orders.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExchangeTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExchangeTradeId")
                        .HasColumnType("text");

                    b.Property<decimal>("Fee")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("FeeAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMaker")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeTradeId");

                    b.HasIndex("OrderId");

                    b.ToTable("Executions", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AverageFillPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExchangeAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExchangeOrderId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExchangeTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FilledQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("ExchangeAccountId");

                    b.HasIndex("ExchangeOrderId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("StrategyVersionId");

                    b.HasIndex("BotId", "Status", "CreatedAt");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Orders.OrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderEvents", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableBalanceAtEntry")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("EquityAtEntry")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("EstimatedEntryFee")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("EstimatedExitFee")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("EstimatedSlippage")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("EstimatedTotalRisk")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Fees")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("InitialRiskUsdt")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Leverage")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("LiquidationPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("MarginUsdt")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("MaxAdverseExcursion")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxFavorableExcursion")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NotionalUsdt")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("RealizedPnL")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("RiskPerTradePercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<decimal>("StopLossPercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("StopLossPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TakeProfitPercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("TakeProfitPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("UnrealizedPnL")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotId", "Symbol", "ClosedAt");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Positions.PositionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RealizedPnLDelta")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("PositionEvents", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Risk.RiskProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowLive")
                        .HasColumnType("boolean");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConsecutiveLosses")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxDailyLossPercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("MaxLeverage")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("MaxPortfolioRiskPercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<int>("MaxSimultaneousPositions")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinimumLiquidationSafetyBufferPercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RiskPerTradePercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("StopLossPercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("TakeProfitPercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RiskProfiles", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Signals.Signal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SignalType")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Timeframe")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("StrategyVersionId");

                    b.HasIndex("BotId", "Timestamp");

                    b.ToTable("Signals", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Strategies.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedSide")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("AllowedSymbolsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("AppliesToAllSymbols")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("RiskProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RiskProfileId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Strategies", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Strategies.StrategyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("FirstUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsImmutable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Timeframe")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("StrategyVersions", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Trades.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntryOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<Guid?>("ExitOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Fees")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("HypothesisId")
                        .HasColumnType("text");

                    b.Property<decimal>("MaxAdverseExcursion")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxFavorableExcursion")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PnL")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("PnLPercent")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SignalAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StrategyFamily")
                        .HasColumnType("text");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntryOrderId");

                    b.HasIndex("ExitOrderId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("StrategyVersionId");

                    b.HasIndex("BotId", "ClosedAt");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("TradingPlatform.Domain.Backtesting.Backtest", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Strategies.StrategyVersion", "StrategyVersion")
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Backtesting.BacktestRun", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Backtesting.Backtest", "Backtest")
                        .WithMany("Runs")
                        .HasForeignKey("BacktestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Backtest");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Backtesting.BacktestTrade", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Backtesting.BacktestRun", "BacktestRun")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Balances.Balance", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Bots.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId");

                    b.HasOne("TradingPlatform.Domain.Exchanges.ExchangeAccount", "ExchangeAccount")
                        .WithMany()
                        .HasForeignKey("ExchangeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("ExchangeAccount");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Balances.BalanceSnapshot", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Exchanges.ExchangeAccount", "ExchangeAccount")
                        .WithMany()
                        .HasForeignKey("ExchangeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeAccount");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Bots.Bot", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Exchanges.ExchangeAccount", "ExchangeAccount")
                        .WithMany()
                        .HasForeignKey("ExchangeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Risk.RiskProfile", "RiskProfile")
                        .WithMany()
                        .HasForeignKey("RiskProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Strategies.StrategyVersion", "StrategyVersion")
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeAccount");

                    b.Navigation("RiskProfile");

                    b.Navigation("StrategyVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Bots.BotRun", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Bots.Bot", "Bot")
                        .WithMany("Runs")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Exchanges.ExchangeAccount", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Exchanges.ExchangeCredential", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Exchanges.ExchangeAccount", "ExchangeAccount")
                        .WithOne("Credential")
                        .HasForeignKey("TradingPlatform.Domain.Exchanges.ExchangeCredential", "ExchangeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeAccount");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Identity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Identity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Market.MarketCandle", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Market.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Market.MarketTrade", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Market.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Operations.Notification", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Orders.Execution", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Orders.Order", "Order")
                        .WithMany("Executions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Orders.Order", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Bots.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Exchanges.ExchangeAccount", "ExchangeAccount")
                        .WithMany()
                        .HasForeignKey("ExchangeAccountId");

                    b.HasOne("TradingPlatform.Domain.Strategies.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Strategies.StrategyVersion", "StrategyVersion")
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("ExchangeAccount");

                    b.Navigation("Strategy");

                    b.Navigation("StrategyVersion");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Orders.OrderEvent", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Orders.Order", "Order")
                        .WithMany("Events")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Positions.Position", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Bots.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Positions.PositionEvent", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Positions.Position", "Position")
                        .WithMany("Events")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Risk.RiskProfile", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Signals.Signal", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Bots.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Strategies.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Strategies.StrategyVersion", "StrategyVersion")
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("Strategy");

                    b.Navigation("StrategyVersion");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Strategies.Strategy", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Risk.RiskProfile", "RiskProfile")
                        .WithMany()
                        .HasForeignKey("RiskProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TradingPlatform.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Strategies.StrategyVersion", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Strategies.Strategy", "Strategy")
                        .WithMany("Versions")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Trades.Trade", b =>
                {
                    b.HasOne("TradingPlatform.Domain.Bots.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Orders.Order", "EntryOrder")
                        .WithMany()
                        .HasForeignKey("EntryOrderId");

                    b.HasOne("TradingPlatform.Domain.Orders.Order", "ExitOrder")
                        .WithMany()
                        .HasForeignKey("ExitOrderId");

                    b.HasOne("TradingPlatform.Domain.Strategies.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatform.Domain.Strategies.StrategyVersion", "StrategyVersion")
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("EntryOrder");

                    b.Navigation("ExitOrder");

                    b.Navigation("Strategy");

                    b.Navigation("StrategyVersion");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Backtesting.Backtest", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Backtesting.BacktestRun", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Bots.Bot", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Exchanges.ExchangeAccount", b =>
                {
                    b.Navigation("Credential");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Orders.Order", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Executions");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Positions.Position", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TradingPlatform.Domain.Strategies.Strategy", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
